spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
  batch:
    job:
      enabled: false

server:
  port: 8081
logging:
  level:
    project.airbnb.clone: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

app:
  frontend-url: http://localhost:3000
  base-url: http://localhost:8081