spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081

tourapi:
  key: ${TOUR_API_KEY}