[[Wishlist-API-create]]
=== 위시리스트 생성
operation::wishlist-controller-test/create-wishlist[snippets='http-request,request-headers,request-body,request-fields,response-body,response-fields']

[[Wishlist-API-add-accommodation]]
=== 위시리스트에 숙소 저장
operation::wishlist-controller-test/add-accommodation[snippets='http-request,path-parameters,request-headers,request-body,request-fields,http-response']

[[Wishlist-API-remove-accommodation]]
=== 위시리스트에서 숙소 제거
operation::wishlist-controller-test/remove-accommodation[snippets='http-request,path-parameters,request-headers,http-response']

[[Wishlist-API-update-wishlist-name]]
=== 위시리스트의 이름 변경
operation::wishlist-controller-test/update-wishlist-name[snippets='http-request,path-parameters,request-headers,request-body,request-fields,http-response']

[[Wishlist-API-remove-wishlist]]
=== 위시리스트 제거
operation::wishlist-controller-test/remove-wishlist[snippets='http-request,path-parameters,request-headers,http-response']

[[Wishlist-API-wishlist]]
=== 위시리스트 조회
operation::wishlist-controller-test/get-accommodations-from-wishlist[snippets='http-request,path-parameters,request-headers,http-response,response-body,response-fields']

[[Wishlist-API-update-memo]]
=== 위시리스트 숙소의 메모 수정
operation::wishlist-controller-test/update-memo[snippets='http-request,path-parameters,request-headers,request-body,request-fields,http-response']
